package com.conant.order.vo;

// Generated 2008-11-16 19:21:15 by Hibernate Tools 3.2.1.GA

/**
 * OrsFrameDetail generated by hbm2java
 */

public class FrameDetail implements java.io.Serializable
{
	private int id;
	private OrsOrder orsorder;
	private FrameColor framecolor;
	private FrameModel framemodel;
	private Integer rboxasize;
	private Integer lboxasize;
	private Integer rboxbsize;
	private Integer lboxbsize;
	private Float rfittingheight;
	private Float lfittingheight;
	private Float rdistance;
	private Float ldistance;
	private Float dbl;

	public FrameDetail()
	{
	}

	public FrameDetail(int id, OrsOrder orsorder, FrameModel framemodel)
	{
		this.id = id;
		this.orsorder = orsorder;
		this.framemodel = framemodel;
	}

	public FrameDetail(int id, OrsOrder orsorder, FrameColor framecolor,
			FrameModel framemodel, Integer rboxasize, Integer lboxasize,
			Integer rboxbsize, Integer lboxbsize, Float rfittingheight,
			Float lfittingheight, Float rdistance, Float ldistance, Float dbl)
	{
		this.id = id;
		this.orsorder = orsorder;
		this.framecolor = framecolor;
		this.framemodel = framemodel;
		this.rboxasize = rboxasize;
		this.lboxasize = lboxasize;
		this.rboxbsize = rboxbsize;
		this.lboxbsize = lboxbsize;
		this.rfittingheight = rfittingheight;
		this.lfittingheight = lfittingheight;
		this.rdistance = rdistance;
		this.ldistance = ldistance;
		this.dbl = dbl;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public OrsOrder getOrsorder()
	{
		return this.orsorder;
	}

	public void setOrsorder(OrsOrder orsorder)
	{
		this.orsorder = orsorder;
	}

	public FrameColor getFramecolor()
	{
		return this.framecolor;
	}

	public void setFramecolor(FrameColor framecolor)
	{
		this.framecolor = framecolor;
	}

	public FrameModel getFramemodel()
	{
		return this.framemodel;
	}

	public void setFramemodel(FrameModel framemodel)
	{
		this.framemodel = framemodel;
	}

	public Integer getRboxasize()
	{
		return this.rboxasize;
	}

	public void setRboxasize(Integer rboxasize)
	{
		this.rboxasize = rboxasize;
	}

	public Integer getLboxasize()
	{
		return this.lboxasize;
	}

	public void setLboxasize(Integer lboxasize)
	{
		this.lboxasize = lboxasize;
	}

	public Integer getRboxbsize()
	{
		return this.rboxbsize;
	}

	public void setRboxbsize(Integer rboxbsize)
	{
		this.rboxbsize = rboxbsize;
	}

	public Integer getLboxbsize()
	{
		return this.lboxbsize;
	}

	public void setLboxbsize(Integer lboxbsize)
	{
		this.lboxbsize = lboxbsize;
	}

	public Float getRfittingheight()
	{
		return this.rfittingheight;
	}

	public void setRfittingheight(Float rfittingheight)
	{
		this.rfittingheight = rfittingheight;
	}

	public Float getLfittingheight()
	{
		return this.lfittingheight;
	}

	public void setLfittingheight(Float lfittingheight)
	{
		this.lfittingheight = lfittingheight;
	}

	public Float getRdistance()
	{
		return this.rdistance;
	}

	public void setRdistance(Float rdistance)
	{
		this.rdistance = rdistance;
	}

	public Float getLdistance()
	{
		return this.ldistance;
	}

	public void setLdistance(Float ldistance)
	{
		this.ldistance = ldistance;
	}

	public Float getDbl()
	{
		return this.dbl;
	}

	public void setDbl(Float dbl)
	{
		this.dbl = dbl;
	}
}
