package com.conant.order.vo;
// Generated 2008-11-16 19:21:15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * OrsFramecolor generated by hbm2java
 */

public class FrameColor  implements java.io.Serializable {


     private Integer id;
     private String code;
     private Set<FrameDetail> framedetails = new HashSet<FrameDetail>(0);

    public FrameColor() {
    }

	
    public FrameColor(String code) {
        this.code = code;
    }
    public FrameColor(String code, Set<FrameDetail> framedetails) {
       this.code = code;
       this.framedetails = framedetails;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public Set<FrameDetail> getFramedetails() {
        return this.framedetails;
    }
    
    public void setFramedetails(Set<FrameDetail> framedetails) {
        this.framedetails = framedetails;
    }
}
