package com.conant.order.vo;
// Generated 2008-11-16 19:21:15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * OrsLensModel generated by hbm2java
 */
public class LensModel  implements java.io.Serializable {
     private Integer id;
     private int lenstype;
     private int opticaltype;
     private int lenscolor;
     private int lenscoating;
     private int customizable;
     private String lensmodel;
     private Set<LensDetail> lensdetails = new HashSet<LensDetail>(0);

    public LensModel() {
    }

	
    public LensModel(int lenstype, int opticaltype, int lenscolor, int lenscoating, int customizable, String lensmodel) {
        this.lenstype = lenstype;
        this.opticaltype = opticaltype;
        this.lenscolor = lenscolor;
        this.lenscoating = lenscoating;
        this.customizable = customizable;
        this.lensmodel = lensmodel;
    }
    public LensModel(int lenstype, int opticaltype, int lenscolor, int lenscoating, int customizable, String lensmodel, Set<LensDetail> lensdetails) {
       this.lenstype = lenstype;
       this.opticaltype = opticaltype;
       this.lenscolor = lenscolor;
       this.lenscoating = lenscoating;
       this.customizable = customizable;
       this.lensmodel = lensmodel;
       this.lensdetails = lensdetails;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public int getLenstype() {
        return this.lenstype;
    }
    
    public void setLenstype(int lenstype) {
        this.lenstype = lenstype;
    }
    
    public int getOpticaltype() {
        return this.opticaltype;
    }
    
    public void setOpticaltype(int opticaltype) {
        this.opticaltype = opticaltype;
    }
    
    public int getLenscolor() {
        return this.lenscolor;
    }
    
    public void setLenscolor(int lenscolor) {
        this.lenscolor = lenscolor;
    }
    
    public int getLenscoating() {
        return this.lenscoating;
    }
    
    public void setLenscoating(int lenscoating) {
        this.lenscoating = lenscoating;
    }
    
    public int getCustomizable() {
        return this.customizable;
    }
    
    public void setCustomizable(int customizable) {
        this.customizable = customizable;
    }
    
    public String getLensmodel() {
        return this.lensmodel;
    }
    
    public void setLensmodel(String lensmodel) {
        this.lensmodel = lensmodel;
    }
    
    public Set<LensDetail> getLensdetails() {
        return this.lensdetails;
    }
    
    public void setLensdetails(Set<LensDetail> lensdetails) {
        this.lensdetails = lensdetails;
    }
}
