package com.conant.order.vo;
// Generated 2008-11-16 19:21:15 by Hibernate Tools 3.2.1.GA

/**
 * OrsLensDetail generated by hbm2java
 */
public class LensDetail  implements java.io.Serializable {
     private Integer id;
     private OrsOrder orsorder;
     private LensModel lensmodel;
     private float diameter;
     private float rsphere;
     private float lsphere;
     private float rcylinder;
     private float lcylinder;
     private Float radd;
     private Float ladd;
     private Float raxis;
     private Float laxis;
     private Integer rvpd;
     private Integer lvpd;
     private Float rvprism;
     private Float lvprism;
     private Integer rhpd;
     private Integer lhpd;
     private Float rhprism;
     private Float lhprism;
     private Integer tinttype;
     private Integer tintcolor1;
     private Integer tintpercentage1;
     private Integer tintcolor2;
     private Integer tintpercentage2;
     private Float rbasecurve;
     private Float lbasecurve;
     private Float decentration;
     private Float redgethickness;
     private Float ledgethickness;
     private Float rcenterthickness;
     private Float lcenterthickness;

    public LensDetail() {
    }

	
    public LensDetail(Integer id, OrsOrder orsorder, LensModel lensmodel, float diameter, float rsphere, float lsphere, float rcylinder, float lcylinder) {
        this.id = id;
        this.orsorder = orsorder;
        this.lensmodel = lensmodel;
        this.diameter = diameter;
        this.rsphere = rsphere;
        this.lsphere = lsphere;
        this.rcylinder = rcylinder;
        this.lcylinder = lcylinder;
    }
    public LensDetail(Integer id, OrsOrder orsorder, LensModel lensmodel, float diameter, float rsphere, float lsphere, float rcylinder, float lcylinder, Float radd, Float ladd, Float raxis, Float laxis, Integer rvpd, Integer lvpd, Float rvprism, Float lvprism, Integer rhpd, Integer lhpd, Float rhprism, Float lhprism, Integer tinttype, Integer tintcolor1, Integer tintpercentage1, Integer tintcolor2, Integer tintpercentage2, Float rbasecurve, Float lbasecurve, Float decentration, Float redgethickness, Float ledgethickness, Float rcenterthickness, Float lcenterthickness) {
       this.id = id;
       this.orsorder = orsorder;
       this.lensmodel = lensmodel;
       this.diameter = diameter;
       this.rsphere = rsphere;
       this.lsphere = lsphere;
       this.rcylinder = rcylinder;
       this.lcylinder = lcylinder;
       this.radd = radd;
       this.ladd = ladd;
       this.raxis = raxis;
       this.laxis = laxis;
       this.rvpd = rvpd;
       this.lvpd = lvpd;
       this.rvprism = rvprism;
       this.lvprism = lvprism;
       this.rhpd = rhpd;
       this.lhpd = lhpd;
       this.rhprism = rhprism;
       this.lhprism = lhprism;
       this.tinttype = tinttype;
       this.tintcolor1 = tintcolor1;
       this.tintpercentage1 = tintpercentage1;
       this.tintcolor2 = tintcolor2;
       this.tintpercentage2 = tintpercentage2;
       this.rbasecurve = rbasecurve;
       this.lbasecurve = lbasecurve;
       this.decentration = decentration;
       this.redgethickness = redgethickness;
       this.ledgethickness = ledgethickness;
       this.rcenterthickness = rcenterthickness;
       this.lcenterthickness = lcenterthickness;
    }

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public OrsOrder getOrsorder() {
        return this.orsorder;
    }
    
    public void setOrsorder(OrsOrder orsorder) {
        this.orsorder = orsorder;
    }

    public LensModel getLensmodel() {
        return this.lensmodel;
    }
    
    public void setLensmodel(LensModel lensmodel) {
        this.lensmodel = lensmodel;
    }
    
    public float getDiameter() {
        return this.diameter;
    }
    
    public void setDiameter(float diameter) {
        this.diameter = diameter;
    }
    
    public float getRsphere() {
        return this.rsphere;
    }
    
    public void setRsphere(float rsphere) {
        this.rsphere = rsphere;
    }
    
    public float getLsphere() {
        return this.lsphere;
    }
    
    public void setLsphere(float lsphere) {
        this.lsphere = lsphere;
    }
    
    public float getRcylinder() {
        return this.rcylinder;
    }
    
    public void setRcylinder(float rcylinder) {
        this.rcylinder = rcylinder;
    }
    
    public float getLcylinder() {
        return this.lcylinder;
    }
    
    public void setLcylinder(float lcylinder) {
        this.lcylinder = lcylinder;
    }
    
    public Float getRadd() {
        return this.radd;
    }
    
    public void setRadd(Float radd) {
        this.radd = radd;
    }
    
    public Float getLadd() {
        return this.ladd;
    }
    
    public void setLadd(Float ladd) {
        this.ladd = ladd;
    }
    
    public Float getRaxis() {
        return this.raxis;
    }
    
    public void setRaxis(Float raxis) {
        this.raxis = raxis;
    }
    
    public Float getLaxis() {
        return this.laxis;
    }
    
    public void setLaxis(Float laxis) {
        this.laxis = laxis;
    }
    
    public Integer getRvpd() {
        return this.rvpd;
    }
    
    public void setRvpd(Integer rvpd) {
        this.rvpd = rvpd;
    }
    
    public Integer getLvpd() {
        return this.lvpd;
    }
    
    public void setLvpd(Integer lvpd) {
        this.lvpd = lvpd;
    }
    
    public Float getRvprism() {
        return this.rvprism;
    }
    
    public void setRvprism(Float rvprism) {
        this.rvprism = rvprism;
    }
    
    public Float getLvprism() {
        return this.lvprism;
    }
    
    public void setLvprism(Float lvprism) {
        this.lvprism = lvprism;
    }
    
    public Integer getRhpd() {
        return this.rhpd;
    }
    
    public void setRhpd(Integer rhpd) {
        this.rhpd = rhpd;
    }
    
    public Integer getLhpd() {
        return this.lhpd;
    }
    
    public void setLhpd(Integer lhpd) {
        this.lhpd = lhpd;
    }
    
    public Float getRhprism() {
        return this.rhprism;
    }
    
    public void setRhprism(Float rhprism) {
        this.rhprism = rhprism;
    }
    
    public Float getLhprism() {
        return this.lhprism;
    }
    
    public void setLhprism(Float lhprism) {
        this.lhprism = lhprism;
    }
    
    public Integer getTinttype() {
        return this.tinttype;
    }
    
    public void setTinttype(Integer tinttype) {
        this.tinttype = tinttype;
    }
    
    public Integer getTintcolor1() {
        return this.tintcolor1;
    }
    
    public void setTintcolor1(Integer tintcolor1) {
        this.tintcolor1 = tintcolor1;
    }
    
    public Integer getTintpercentage1() {
        return this.tintpercentage1;
    }
    
    public void setTintpercentage1(Integer tintpercentage1) {
        this.tintpercentage1 = tintpercentage1;
    }
    
    public Integer getTintcolor2() {
        return this.tintcolor2;
    }
    
    public void setTintcolor2(Integer tintcolor2) {
        this.tintcolor2 = tintcolor2;
    }
    
    public Integer getTintpercentage2() {
        return this.tintpercentage2;
    }
    
    public void setTintpercentage2(Integer tintpercentage2) {
        this.tintpercentage2 = tintpercentage2;
    }
    
    public Float getRbasecurve() {
        return this.rbasecurve;
    }
    
    public void setRbasecurve(Float rbasecurve) {
        this.rbasecurve = rbasecurve;
    }
    
    public Float getLbasecurve() {
        return this.lbasecurve;
    }
    
    public void setLbasecurve(Float lbasecurve) {
        this.lbasecurve = lbasecurve;
    }
    
    public Float getDecentration() {
        return this.decentration;
    }
    
    public void setDecentration(Float decentration) {
        this.decentration = decentration;
    }
    
    public Float getRedgethickness() {
        return this.redgethickness;
    }
    
    public void setRedgethickness(Float redgethickness) {
        this.redgethickness = redgethickness;
    }
    
    public Float getLedgethickness() {
        return this.ledgethickness;
    }
    
    public void setLedgethickness(Float ledgethickness) {
        this.ledgethickness = ledgethickness;
    }
    
    public Float getRcenterthickness() {
        return this.rcenterthickness;
    }
    
    public void setRcenterthickness(Float rcenterthickness) {
        this.rcenterthickness = rcenterthickness;
    }
    
    public Float getLcenterthickness() {
        return this.lcenterthickness;
    }
    
    public void setLcenterthickness(Float lcenterthickness) {
        this.lcenterthickness = lcenterthickness;
    }
}
